version: 2.1

executors:
  arm64-executor:
    docker:
      - image: cimg/openjdk:21.0.1-node
    resource_class: arm.medium

jobs:
  build:
    executor: arm64-executor
    steps:
      - checkout
      - run:
          name: Set up JDK 21
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-21-jdk
            java -version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Cache Maven Packages
          command: |
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn clean spring-boot:build-image -Dmaven.test.skip=true
      - run:
          name: Get POM Version
          command: echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $BASH_ENV
      - run:
          name: Login to Docker Hub
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push phammings/airbnb-clone:${POM_VERSION}
      - run:
          name: Notify Coolify
          command: |
            curl --request GET "${COOLIFY_WEBHOOK}" --header "Authorization: Bearer ${COOLIFY_TOKEN}"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - backend-deploy
