services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/phammings/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=secret
    ports:
      - 127.0.0.1:5432:5432